[supervisord]
nodaemon=true

[program:ttyd]
command=/usr/local/bin/ttyd -p 7681 -W /bin/bash -l
directory=/workspace
autorestart=true

[program:git-sync]
command=/git-sync.sh
directory=/workspace
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=false
