[supervisord]
nodaemon=true


[program:ttyd]

command=/usr/local/bin/ttyd \
    -p 7681 \
    -W \
    bash -l

autorestart=true


[program:nginx]

command=/usr/sbin/nginx -g "daemon off;"

autorestart=true
